<?php 
 return array (
  'single_mode' => 'array (
  \'seller_general_order\' => \'1\',
  \'seller_search_order\' => \'0\',
  \'seller_answer_order\' => \'0\',
  \'seller_qrcode_order\' => \'1\',
)',
  'buyer_join_condition' => '',
  'seller_join_condition' => '',
  'buyer_update_order_type' => '8',
  'seller_push_nums' => '1',
  'seller_check_time' => '21',
  'seller_start_time' => '2014-12-24',
  'buyer_artificial_check' => '0',
  'buyer_buy_time_limit' => '',
  'seller_detail_desc' => '<table class="table" border="1"><thead><tr><th>标准</th><th>集市卖家</th><th>天猫卖家</th></tr></thead><tbody><tr><td>信誉等级</td><td>2钻及以上</td><td>不限</td></tr><tr><td>动态评分</td><td>同行持平以上</td><td>同行持平以上</td></tr><tr><td>报名数量</td><td>》200件</td><td>》200件</td></tr><tr><td>商品评价</td><td>&gt;10条</td><td>&gt;10条</td></tr><tr><td>是否样品</td><td>酌情收取</td><td>酌情收取</td></tr><tr><td>发货速度</td><td>1-3日发货</td><td>1-3日发货</td></tr><tr><td>历史价格</td><td>&gt;本期活动价</td><td>&gt;本期活动价</td></tr><tr><td>审核周期</td><td>&gt;15个工作日</td><td>&gt;15个工作日</td></tr><tr><td>预告方式</td><td>&gt;需预告、无预告</td><td>&gt;需预告、无预告</td></tr><tr><td>重复周期</td><td>&gt;15天后</td><td>&gt;15天后</td></tr><tr><td>店内客服</td><td>&gt;必须在线</td><td>&gt;必须在线</td></tr></tbody></table><p><br/><br/><br/><br/></p>',
  'buyer_good_buy_times' => '1',
  'rebate_isopen' => '1',
  'seller_discount_range' => 'array (
  \'min\' => \'0.1\',
  \'max\' => \'9.9\',
)',
  'seller_no_check_order' => '3',
  'seller_push_days' => '7',
  'buyer_update_order_sn' => '111',
  'buyer_write_order_time' => '60',
  'rebate_price_name' => '网购价',
  'buyer_day_buy_times' => '',
  'seller_activity_desc' => '单个商品参团，高性价比优先。报名价格需≥20元，折扣范围在0.1-5折内，审核通过后获得排期，活动时间最长可报名30 天。',
  'rebate_name' => '购物返利',
  'seller_end_time' => '2017-12-15',
  'seller_get_appeal' => 'array (
  \'time\' => \'24\',
  \'check\' => \'2\',
)',
  'buyer_check_update_order_sn' => '48',
  'service_type' => '2',
);
?>