<?php 
/**
 * @version        $Id$
 * @author         master@xuewl.com
 * @copyright      Copyright (c) 2007 - 2014, Chongqing xuewl Information Technology Co., Ltd.
 * @link           http://www.xuewl.com
**/
return array(
	'please_add_category' => '请先添加栏目',
	'search_category'     => '输入“拼音”或者“栏目名称”可快速搜索',
	'quick_into'          => '快速进入',
	'checkall_content'    => '审核内容',
	
	'title_is_empty'      => '标题不能为空',

	'add_content'          => '添加内容',
	'check_passed'         => '审核通过',
	'check_unpassed'     => '待审核内容',
	'update_htmls'         => '批量更新_{catname}_列表',
	'elite'                => '推荐',
	'no_elite'             => '不推荐',
	'related_articles'     => '相关文章',
	'top'                  => '排行榜',
	'relevant_articles_id' => '相关文章id',
	'key_word'             => '关键词',
	'reject'               => '退稿',
	'publish_user'         => '发布人',
	'today_hits'           => '今日点击',
	'yestoday_hits'        => '昨日点击',
	'week_hits'            => '本周点击',
	'month_hits'           => '本月点击',
	'member_contribute'    => '会员投稿',
	'comment'              => '评论',
	'createhtml'           => '批量生成HTML',
	'passed_checked'       => '通过审核',
	'view_comment'         => '查看评论',
	'copyfrom_tips'        => '≡请选择≡',

	'c_status'                => '状态',
	'c_publish'               => '已发布',
	'c_check'                 => '待审核',
	'save_close'              => '保存后自动关闭',
	'save_continue'           => '保存并继续发表',
	'c_close'                 => '关闭(X)',
	'dialog_close'            => '关闭',
	'please_save_information' => '您编辑的文章内容还没有进行保存！',
	'page_manage'             => '单网页管理',
	'title'                   => '标题',
	'intro'                   => '简介',
	'hits'                    => '点击量',
	'keywords'                => '关键词',
	'content'                 => '内容',
	'c_template'              => '模板',

	'push' => '推送',
	'remove' => '批量移动',

	'updatetime'      => '更新时间',
	'updatetime_desc' => '更新时间降序',
	'listorder_asc'   => '排序升序',
	'listorder_desc'  => '排序降序',
	'addtime'         => '添加时间',

'explode_keywords'      => '多关键词之间用空格或者“,”隔开',
'add_content_position'  => '当前位置：内容  > 内容发布管理 > 添加内容',
'edit_content_position' => '当前位置：内容  > 内容发布管理 > 修改内容',
'vistor'        => '链接地址',
'click_vistor' => '点击访问',
'visualization_edit' => '碎片管理',

'items'                     => '数据量',
'tablename'                 => '数据表',
'model_manage'              => '模型管理',
'field_manage'              => '字段管理',
'model_tablename'           => '模型表键名',
'description'               => '描述',
'template_setting'          => '模板设置',
'model_tablename_wrong'     => '表名必须为字母、数字、下划线',
'already_exist'             => '已经存在',
'between_1_to_20'           => '长度必须为1-20位',
'connecting_please_wait'    => '正在连接...请稍等',
'thumb'                     => '缩略图',
'all_list'                  => '所有文章',
'all_check_list'            => '所有待审内容',
'thumb_list'                => '包含缩略图',
'block_site_index'          => '站点首页',
'checkall_content'          => '审核内容',
'publish_to_othor_category' => '同时发布到其他栏目',
'field_disabled'            => '禁用',
'field_enabled'             => '<font color="red"> 启用</font>',
'confirm_delete_model'      => '确认要删除 『 {message} 』 吗？删除后，数据表将同时被删除！',
'available_styles'       => '可用风格：',
'category_index_tpl'     => '栏目首页模板',
'category_list_tpl'      => '栏目列表页模板',
'content_tpl'            => '内容页模板',
'other_template_setting' => '其他模板设置',
'admin_content_list'     => '后台信息管理模板：',
'member_content_add'     => '会员中心信息添加模板：',


'unique' => '值唯一',
'basic_field' => '作为基本信息',
'basic_field_tips' => '基本信息将在添加页面左侧显示',
'as_search_field' => '作为搜索条件',
'allow_contributor' => '在前台投稿中显示',
'as_fulltext_field' => '作为全站搜索信息',
'as_postion_info' => '在推荐位标签中调用',
'disabled_groups_field' => '禁止设置字段值的会员组',
'disabled_role_field' => '禁止设置字段值的角色',
'edit_field' => '修改字段',
'field_disabled' => '禁用',
'field_enabled' => '<font color="red"> 启用</font>',
'import_model' => '导入模型',
'edit_model' => '编辑模型',
'export' => '导出',
'template' => '选择模板',
'type_name' => '类别名称',
'edit_type' => '编辑类别',
'updateurl_tips' => '1、仅当内容页URL规则发上变化时，请批量更新，地址未改变时，不需要更新 。<BR>2、规则设置：设置 > 相关设置 > 管理栏目 > 添加或修改栏目',

'as_omnipotent_field' => '作为万能字段的附属字段',
'as_omnipotent_field_tips' => '必须与万能字段结合起来使用，否则内容添加的时候不会正常显示',

'issystem_field' => '作为主表字段',
'check_title' => '检测重复',
'title_repeat' => '标题重复',
'title_not_repeat' => '标题不重复',
'mirror_server_list' => '镜像服务器列表',
'attachment_upload' => '附件上传',
'upload_soft' => '上传软件',
'file_list' => '文件列表',
'multiple_file_list' => '多文件上传',
'add_remote_url' => '添加远程地址',
'remove_out' => '移除',
'upload_pic' => '上传图片',
'upload_pic_max' => '您最多可以同时上传',
'pic_list' => '图片列表',
'select_pic' => '选择图片',
'tips_pics' => '张',
'islink_url' => '转向链接',
'page_type1' => '不分页',
'page_type2' => '自动分页',
'page_type3' => '手动分页',
'page_maxlength' => '字符数（包含HTML标记）',
'upload_thumbnails' => '请先上传缩略图',
'edit_content' => '编辑：',
'not_meet_the_conditions' => '不符合要求',
'not_less_than' => '不得少于',
'not_more_than' => '不得多于',
'the_value_must_not_repeat' => '的值不得重复！',


'addmark' => '点击标注位置',
'editmark' => '修改标注位置',
'mapmark' => '地图标注',

'cancel_the_picture'   => '取消图片',
'cut_the_picture'      => '裁切图片',
'moreinfo'             => '调用副表',
'contribute_add_point' => '投稿奖励',
'view_video'           => '预览视频',
'change_thumb'         => '更换缩略图',

'according_model' => '按照模型更新',
'select_category_area' => '选择栏目范围',
'select_operate_content' => '选择操作内容',
'no_limit_category' => '不限栏目',
'every_time' => '每轮更新',
'information_items' => '条信息',
'update_all' => '更新所有信息',
'submit_start_update' => '开始更新',
'no_limit_model' => '不限模型',
'last_information' => '更新最新发布的',
'update_time_from' => '更新发布时间从',
'to' => '到',
'in_information' => '的信息',
'update_id_from' => '更新ID从',

'type'                   => '审核状态',
'unpassed'          => '待审核',
'passed'               => '已审核',
);