<?php 
 return array (
  'seller_check_time' => '1',
  'seller_join_condition' => 'array (
  \'information\' => \'6\',
)',
  'bonus_content' => '红包',
  'trial_name' => '红包试用',
  'seller_activity_desc' => '单个商品参团，高价值商品优先，审核通过后获得排期，活动时间最长30天，',
  'bonus_price' => 'array (
  \'min\' => \'0.1\',
  \'max\' => \'300\',
)',
  'seller_charge_name' => '推广费',
  'buyer_join_condition' => '',
  'buyer_check_update_order_sn' => '72',
  'trial_isopen' => '1',
  'seller_vip_isopen' => '1',
  'buyer_day_buy_times' => '10',
  'bonus_isopen' => '1',
  'buyer_continuity_apply' => '0',
  'seller_give_back' => '1',
  'seller_start_time' => '2016-12-22',
  'seller_pat_isopen' => '0',
  'seller_point_isopen' => '0',
  'seller_trialtalk_check' => 'array (
  \'value\' => \'5\',
  \'chose\' => \'0\',
)',
  'seller_push_nums' => '1',
  'single_mode' => 'array (
  \'seller_general_order\' => \'1\',
  \'seller_search_order\' => \'0\',
  \'seller_answer_order\' => \'0\',
  \'seller_qrcode_order\' => \'1\',
)',
  'seller_ordersn_check' => '23',
  'trial_price_name' => '试用价',
  'bonus_name' => '闪电佣金',
  'seller_detail_desc' => '<p>单个商品页面显示，高性价比优先。<br/></p>',
  'bonus_ratio' => '1:0.5',
  'buyer_good_buy_times' => '10',
  'seller_push_days' => '10',
  'seller_order_check_time' => '120',
  'seller_charge_money' => '0',
  'bonus_exchange' => '1',
  'seller_bonus_isopen' => '1',
  'seller_end_time' => '2016-12-31',
  'buyer_write_order_time' => '24',
  'buyer_write_talk_time' => '15',
  'trial_point' => '0.1',
  'buyer_order_fee' => '0',
  'trial_fee_price' => '0',
);
?>