<?php
/**
 * @version        $Id$
 * @author         master@xuewl.com
 * @copyright      Copyright (c) 2007 - 2014, Chongqing xuewl Information Technology Co., Ltd.
 * @link           http://www.xuewl.com
**/
return array(
	'email'                            => '邮箱',
	'or'                               => '或者',
	'nickname'                         => '昵称',
	'uid'                              => '用户ID',
	'regtime'                          => '注册时间',
	'lastlogintime'                    => '最后登录',
	'operation'                        => '操作',
	'password'                         => '密码',
	'cofirmpwd'                        => '确认密码',
	'realname'                         => '真实姓名',
	'amount'                           => '当前余额',
	'verify_pass'                      => '通过',
	'ignore'                           => '忽略',
	'reject'                           => '拒绝',
	'verify_status'                    => '审核状态',
	'verify'                           => '审核',
	'verify_message'                   => '审核信息',
	'reg_reject'                       => '您申请注册的账号被拒绝',
	'reg_ignore'                       => '您申请注册的账号被忽略',
	'reg_delete'                       => '您申请注册的账号被删除',
	'reg_pass'                         => '您申请注册的账号已通过',
	'verify_message'                   => '审核信息',
	'verify_message'                   => '审核信息',
	'please_wait_administrator_verify' => '请等待管理员审核。',
	'register_verify_message'          => '邮件认证内容',
	'need_verify'                      => '未审核',
	'pass_verify'                      => '通过审核',
	'nerver_pass'                      => '重名无法通过',
	'sendemail'                        => '发送邮件通知被审核用户',
    /* 核心语言变量 */  
	'username'                => '用户名',
	'add_model'               => '添加模型',
	'member_model'            => '会员模型',
	'member_model_add'        => '添加会员模型',
	'basic_configuration'     => '基本设置',
	'model_import'            => '导入模型',
	'between_2_to_20'         => '应该为2-20位之间',
	'between_2_to_20'         => '应该为2-20位之间',
	'between_6_to_20'         => '应该为6-20位之间',
	'between_1_to_20'         => '应该为1-20位之间',
	'between_2_to_32'         => '应该为2-32位之间',
	'between_2_to_8'          => '应该为2-8位之间',
	'deny_model'              => '是否禁用模型',
	'tablename_already_exist' => '数据表已存在',
	'modelname_already_exist' => '模型名已存在',
	'fieldname'               => '字段名',
	'cnames'                  => '别名',
	'system'                  => '系统',
	'must_input'              => '必填',
	'contribute'              => '投稿',
	'member_modelfield_add'   => '添加模型字段',
	'enable'                  => '启用',
	'disable'                 => '禁用',
	'modify'                  => '修改',
	'field'                   => '字段',
	'manage'                  => '管理',
	'export'                  => '导出',
	
	/* 后台 */
	'filedname'               => '字段名',
	'username_rule'           => '只能由英文字母、数字和下划线组成，并且仅能字母开头，不以下划线结尾',
	'filed_nickname'          => '字段别名',
	'exaple_title'            => '例如：文章标题',
	'field_cue'               => '字段提示',
	'nickname_alert'          => '显示在字段别名下方作为表单输入提示',
	'correlation_param'       => '相关参数',
	'correlation_attribute'   => '设置表单相关属性',
	'extra_attribute'         => '表单附加属性',
	'add_javascript'          => '可以通过此处加入javascript事件',
	'form_css'                => '表单样式名',
	'user_form_css'           => '定义表单的CSS样式名',
	'string_len_range'        => '字符长度取值范围',
	'post_alert'              => '系统将在表单提交时检测数据长度范围是否符合要求，如果不想限制长度请留空',
	'min'                     => '最小值：',
	'max'                     => '最大值：',
	'value'                   => '值',
	'date_regular'            => '数据校验正则',
	'validity_alert'          => '系统将通过此正则校验表单提交的数据合法性，如果不想校验数据请留空',
	'common_regular'          => '常用正则',
	'number'                  => '数字',
	'int'                     => '整数',
	'alphabet'                => '字母',
	'http'                    => '超级链接',
	'mp'                      => '手机号码',
	'tel'                     => '电话号码',
	'postcode'                => '邮政编码',
	'error_alert'             => '校验未通过的提示信息',
	'form_error_alert'        => '当表单数据不满足正在校验时的系统提示信息',
	'unique'                  => '值唯一',
	'can_empty'               => '是否为注册必填信息',
	'search_condition'        => '作为搜索条件',
	'isadd_condition'         => '是否在前台显示',
	'isomnipotent_condition'  => '作为万能字段的附属字段',
	'deny_set_field_group'    => '禁止设置字段值的会员组',
	'deny_set_field_role'     => '禁止设置字段值的角色',
	'points_less_than'        => '您的积分为<font color=>"red">{point}</font>点，发布投稿需要扣除<font color=>"red">{need_point}</font>点，您可以通过回复评论来获取积分',
	'contributors_checked'    => '投稿成功，等待管理员审核',
	'contributors_success'    => '内容已发布！感谢您的投稿！',
	'has_been_verified'       => '投稿已经通过审核，不允许再次修改！',
	'contribute_del_point'    => '投稿扣点',
	'contribute_add_point'    => '投稿奖励',

	'move_member_model_index_alert' => '1、请谨慎删除模型，当模型里存在会员时请使用“移动”功能将该模型里的会员移动到其他会员模型中。<br />2、移动模型会员，将会把原有模型里的会员信息删除，将不能修复。 ',
	'filedname_incorrect' => '字段名称不正确',
	'filedtype_need'      => '请选择字段类型',
	'filedtype'           => '字段类型',
	'input_correct'       => '输入正确',
	'filed_nickname_need' => '请输入别名',

	'member_group_permission' => '用户权限',

	/* 会员组 */
   'member_group' => '会员组',

	'groupid'                     => '用户组id',
	'groupname'                   => '用户组名',
	'issystem'                    => '系统组',
	'starnum'                     => '星星数',
	'pointrange'                  => '积分小于',
	'allowvisit'                  => '访问权限',
	'allowpost'                   => '投稿权限',
	'allowsearch'                 => '搜索权限',
	'allowupgrade'                => '自助升级',
	'allowpostverify'             => '投稿审核',
	'allowsendmessage'            => '发短消息',
	'membernum'                   => '会员数',
	'allowattachment'             => '允许上传附件',
	'member_group_publish_verify' => '投稿不需审核',

	'member_group_name'           => '会员组名称',
	'member_group_access'         => '允许访问',
	'member_group_search'         => '允许搜索',
	'member_group_publish'        => '允许投稿',
	'publish_deny'                => '禁止投稿',
	'member_group_upgrade'        => '允许自助升级',
	'member_group_sendmessage'    => '允许发短消息',
	'member_group_publish_verify' => '投稿不需审核',
	'member_group_dayprice'       => '包日',
	'member_group_monthprice'     => '包月',
	'member_group_yearprice'      => '包年',
	'member_group_maxmessagenum'  => '最大短消息数',
	'allowpostnum'                => '日最大投稿数',
	'zero_nolimit'                => '0为不限制',
	'allowpostnum_deny'           => '今日投稿已超过限制数',
	'member_group_username_color' => '用户名颜色',
	'not_less_than'               => '不得少于',
	'not_more_than'               => '不得多于',
	'member_group_icon'           => '用户组图标',
	'member_group_deny'           => '是否禁用',
	'member_group_creditrange'    => '积分小于',
	'member_group_starnum'        => '星星数',
	'member_group_upgradeprice'   => '升级价格',
	'member_group_sentmessage'    => '允许发送短消息',
	'member_group_sentmessage'    => '允许发送短消息',
	'send_message'                => '发送短消息',
	'member_group_description'    => '简洁描述',
	
	'between_2_to_8'          => '应该为2-8位之间',
	'groupname_already_exist' => '用户组名已存在',
	'between_1_to_8_num'      => '应该为1-8位的数字',
	'maxmessagenum'           => '短消息数',
	'allow_register'          => '允许新会员注册',
	'register_model'          => '注册选择模型',
	'need_more_memberinfo'    => '请填写会员详细信息',
	'register_email_auth'     => '新会员注册需要邮件验证',
	'enablemailcheck_notice'  => '需填写邮箱配置，开启后会员注册审核功能无效',
	'allow_memberlist'        => '允许前台浏览会员列表',
	'register_verify'         => '新会员注册需要管理员审核',
	'administrator'           => '管理员',
	'member_verifycode'       => '会员注册启用验证码功能',
	'click_change_validate'   => '点击更换验证码',
	'upgrade_method'          => '会员升级付费方式',
	'defualtpoint'            => '新会员默认点数',
	'defualtamount'           => '新会员注册默认赠送资金',
	'register_protocol'       => '会员注册协议',
	'show_register_protocol'  => '是否显示注册协议',
	'show_app_point'          => '是否启用应用间积分兑换',
	'rmb_point_rate'          => '1元人民币购买积分数量',
	
	'please_input_mobile'         => '请输入手机号码',
	'get_sms_code'                => '获取短信验证码',
	'checkcode_wrong'             => '验证码错误',
	'sms_tips'                    => '此服务免费,验证码将以短信免费发送到您的手机',
	'sms_checkcode_send_to'       => '此服务免费,验证码已发送到',
	'sms_edit_mobile'             => '修改号码',
	'repeat_send'                 => '如果超过90秒未收到验证码，您可以免费重新获取。',
	'repeat_sms_code'             => '重获短信验证码',
	'receive_sms_code'            => '我收到的手机验证码为：',
	'input_receive_sms_code'      => '请输入手机收到的验证码',
	'input_right_mobile'          => '请输入正确的手机号码',
	'sms_have_reached_the_limit'  => '你今天获取验证码次数已达到上限',
	'sms_send_fail'               => '短信发送失败',
	'wait_second_repeat_sms_code' => '秒后重获验证码',
	'error_sms_code'              => '短信验证码错误，请重新输入',
	'register_func_tips'          => '可用变量：用户名 - {username} ，密码 - {password} ，Email - {email} ，点击认证地址 - {click} ，链接地址：{url}',
	'enablcodecheck'                   => '是否开启验证码',
	'mobile_checktype'                 => '手机强制验证方式',
	'user_sendsms'                     => '用户自发短信验证 ',
	'get_verify'                       => '获取验证码验证',
	'no_checksms'                      => '不验证',
	'user_sendsms_title'               => '用户自发短信提示语',
	'param_error'                      => '参数格式错误',
	'change_mobile'                    => '更换手机',
	'soulbound'                        => '已绑定',
	'new_mobile'                       => '新手机号',
	'use_email_get_password'           => '通过电子邮箱找回密码',
	'use_mobile_get_password'          => '通过手机校验码找回密码',
	'use_username_get_password'        => '通过用户名找回密码',
	'select_find_password_type'        => '请选择密码找回方式',
	'please_wait_administrator_verify' => '请等待管理员审核。',
	'register_verify_message'          => '邮件认证内容',
	'forgetpasswordmessage'            => '密码找回邮件内容',
	/*吉祥卡*/
	'member_card_add' =>'吉祥卡添加',
	'card_title'      =>'吉祥卡套餐',
	'card_discount'   =>'折扣',
	'card_point'      =>'内置点数',
	'card_points'     =>'赠送点数',
	'card_money'      =>'价格',
	'TO'              =>'到',
	'sure_delete'     =>'确认删除',
	'card_msg'        =>'吉祥卡介绍',
	'is_hot'          => '是否热销',
	'upload_soft'  =>'上传软件',
	/*日志*/
	'subject'                 => '标题',
	'content'                 => '内容',
	'type'                            =>'类型',
	'addtime'                       =>'发布时间',
	
	'setting'                 => '配置',
	'remove_all_selected'     => '删除选中',
	//'username'                => '作者',
	'time'                    => '时 间',
	'see_info'                => '查看详情',
	'no_empty'                => '不能为空',
	'before_select_operation' => '请选择再执行操作',
	
	'no_thisuser'             => '没有此用户',
	'connecting'              => '正在连接，请稍候。',
	
	'group'                   => '按会员组',
	'role'                    => '按角色',
	'send_num'                => '每轮发送次数',
	
	'select'	=> array(
			'send_from_id' => '发件人',
			'send_to_id'	=> '收件人',
	),
	'not_myself'              => '禁止给自己或非注册用户发送消息',
	'sendtime'                => '发送时间',
	'show_m'                  => '显示',
	'details'                 => '查看详情',
	'message_sender'          => '发 信 人',
	'query_type'              => '查询类型',
	'to'                      => '至',
	'target'	=> '目标',
	'audit'							=>	'审核',
	'passed'						=>	'通过',
	'status'                  => '状 态',
	'image'                   =>'图片故事',
	'suffer'                      =>'经验教程',
	'pretty'                         =>'美图精选',
	'confirm'                       =>'确定删除',
	'check'                        =>'审核通过',
	'uncheck'                        =>'审核不通过',
	'loginfo'                    =>'日志详情',
	'hits'                          =>'点击数',
	'introduce'                =>'介绍',
	
	'DENY_REGISTER'   =>'',
	'USER_ALREADY_EXIST'      =>'用户名已存在',
	'PASSWORDS_NOT_MATCH'  =>'两次密码不同',
	'PASSWORDS_MATCH' =>'输入正确',
	'EMAIL_ALREADY_EXIST' => '邮箱已存在',
	'VIP'                                     =>'vip会员',
	'ISVIP'                                   =>'是否为vip会员',
	'OVERDUEDATE'                =>'过期时间',
	'points'                                =>'下载点数',
	'AVATAR'                             =>'头像',
	'IN_SITE_NAME'                  =>'所属站点',
	'memberinfo'                       =>'会员详情',
	'NOT_CHANGE_THE_PASSWORD_PLEASE_LEAVE_A_BLANK' =>'不修改密码请留空。',
	'NOT_CHANGE_THE_PASSWORD_PLEASE_LEAVE_A_BLANK' =>'不修改密码请留空。',
	'CHANGEGROUP_NOTICE'        =>'非vip会员用户组与积分绑定，如只修改会员组请设置该会员为vip',
	'POINT_NOTICE'                        =>'，积分点数将影响会员用户组',
	
	'merchant_add'                        =>'商家添加',
	
	/*vip 商家设置  */
	'merchant_type_add'           =>'商家类型添加',
	'merchant_group_name'     =>'商家类型名称',
	'merchant_group_image'     =>'商家标示',
	
	'aword'                                         =>'奖励',
	'member_aword'                         =>'会员奖励',
	'member_aword_type'                =>'会员奖励类型',
	'member_aword_value'               =>'奖励值',
	'member_aword_cause'          =>'奖励原因',
	/*推荐商家*/
	'member_recommend_add'          =>'添加推荐商家',
 );